### ISSUE TITLE
"python3 ../../extract_gt/extractBB.py -b test_switch -m test_switch.gt -o /tmp/gtBlock_test_switch.pb" meet an error

### ISSUE THREAD

**Issue by island255** [junxzm1990/x86-sok#1]
Hi, I use the script to build a docker image. However, when I try to run

"python3 ../../extract_gt/extractBB.py -b test_switch -m test_switch.gt -o /tmp/gtBlock_test_switch.pb"

Neither python3 nor  ../../extract_gt/extractBB.py exists.

Please check if there is an error.

**Comment by bin2415** [comment]
Hello, thanks for the reporting. In the docker image, it only contains the toolchains that collect ground truth when compiling a binary. It does not contain the toolchains that extract ground truth for now.

I will add the dependencies in the docker image.

**Comment by island255** [comment]
OK. Thank you.

**Comment by bin2415** [comment]
Hello, the docker image is ready [here](https://hub.docker.com/repository/docker/bin2415/py_gt).
