### ISSUE TITLE
Disassembler versions used

### ISSUE THREAD

**Issue by akshithg** [junxzm1990/x86-sok#10]
Hi would you be able to provide the versions of all the disassemblers used?

I understand that the docker image comes with scripts for running the disassemblers but not the disassemblers itself.
And when I tried setting some of them up with the corresponding latest releases and ran them, I ran into issues.

Thanks for you work btw! Great stuff!

**Comment by bin2415** [comment]
Hello, the versions are:

| disassembler | version|
|---------------|--------|
| PSI | 1.0 |
Uroboros| 0.11
Dyninst| 9.3.2
Objdump| 2.30
Ghidra| 9.0.4
McSema| 2.0.0
Angr| 8.19.7.25
BAP| 2.1.0
Radare2| 4.4.0
IDA Pro| 7.4
Binary Ninja| 1.2
