### ISSUE TITLE
There are two other questions when I used angr script and bap script.

### ISSUE THREAD

**Issue by cL0und** [junxzm1990/x86-sok#12]
Hi, it's me again. 

When I used angrBlocks.py, the script raised AttributeError and it seems like that CFGFast of official lib don't have this attribute.
![image](https://user-images.githubusercontent.com/30562775/134158043-f8dbf090-d372-44dd-883e-3c2f3fcfa3bd.png)

And when I used bap script,it also raise error,ad it seems like bap have't the with-no-return plugin by default.
![image](https://user-images.githubusercontent.com/30562775/134158213-d67a2d75-7ef9-4db4-a6c0-59f21edc1a8a.png)

So, Did you do some secondary development? How can I fix the problems?

**Comment by bin2415** [comment]
For angr, we added `function_prologue_matching_addrs` to collect function starts which are found by function prologue. Comment [this](https://github.com/junxzm1990/x86-sok/blob/master/disassemblers/angr/angrBlocks.py#L27) out is fine to extract CFG of angr.

For bap, please install [this plugin](https://github.com/BinaryAnalysisPlatform/bap-toolkit/tree/master/with-no-return) to use the pass `with-no-return`.

**Comment by cL0und** [comment]
Thanks for your prompt reply,I have solved the first item, whereas I meet a few problems when I compiled plugins.I think I will fix it. Happy mid-autumn ;)

**Comment by cL0und** [comment]
I have solved the plugin problem, but it raise an other error info. 
![image](https://user-images.githubusercontent.com/30562775/134610706-037c6481-3e6e-43c6-940b-a7f3762be16f.png)
BTW my bap version is 2.3.0.

**Comment by bin2415** [comment]
Hello @cL0und , I followed this [issue](https://github.com/BinaryAnalysisPlatform/bap/issues/878) to dump cfg of bap. You could install `rcfg` plugin with this [tutorial](https://github.com/BinaryAnalysisPlatform/bap/issues/878#issuecomment-431344202).

**Comment by cL0und** [comment]
I have solved it, think you.Beside I want to know how to use dyninst disassemblers?Is there any tutorial?
![image](https://user-images.githubusercontent.com/30562775/134626761-428e9ba0-57a5-4cd8-ae0a-76d93b521f37.png)
Need I download relative lib in the same dir with dyninstBB.cpp?

**Comment by bin2415** [comment]
Hello, there exists two errors here.

1. Install [dyninst](https://github.com/dyninst/dyninst). 
   `cmake /path/to/dyninst/source -DCMAKE_INSTALL_PREFIX=/usr/local/lib
   make install -jN
`
2. Recompile blocks.pb.cc/h files. I update the makefile [here](https://github.com/junxzm1990/x86-sok/blob/master/disassemblers/dyninst/Makefile#L8)

**Comment by cL0und** [comment]
Ok, Iet me have a try. I had installed it by spark at the first.

**Comment by cL0und** [comment]
Your Makefile seems to have grammar error about missing separator,I replace space with tab. However the process raise desperate output.There are thousands of errors which can not copy all of them.Like this.
![image](https://user-images.githubusercontent.com/30562775/134754689-a4722ffb-8921-4eed-85f8-27bfb051b96a.png)

**Comment by bin2415** [comment]
Hello, I add the [instructions](https://github.com/junxzm1990/x86-sok/commit/6c689fcad64b1156faed3f0cb7a68a9cdb751d0f) to build dyninst.

The errors above seems that the protobuf issues. What is the version of protoc? Mine is `3.17.2`

**Comment by cL0und** [comment]
Finally,I degrade version to yours and reconstruction C file from pb. It's been pretty well worked out.Thanks for your help, it's really a long journey.
