### ISSUE TITLE
How can I use other comparison scripts?

### ISSUE THREAD

**Issue by cL0und** [junxzm1990/x86-sok#14]
Hi, It seems like some comparison script can not be used now? 

For example, I would like to use compareJmpTable.py and compareCFG.py but I notice it requires me to provide [block type](https://github.com/junxzm1990/x86-sok/blob/d3b7391d0dd3a43c6cfa0904d8c648f5582fede4/compare/compareCFG.py#L476) which extract script do not collect.

I find that only a few scripts collect a little type information which seems like not enough to support the comparison I mention.
![image](https://user-images.githubusercontent.com/30562775/140472907-0af06bd2-5f48-4b34-9204-43abc21d5379.png)

So, How can use other comparison script?

**Comment by bin2415** [comment]
Block type is initialized in [extractBB](https://github.com/junxzm1990/x86-sok/blob/d3b7391d0dd3a43c6cfa0904d8c648f5582fede4/extract_gt/BlockUtil.py#L370).

**Comment by cL0und** [comment]
I see, but extractBB is just used to extract ground truth? And It seems like [decompiler plugin](https://github.com/junxzm1990/x86-sok/tree/master/disassemblers) do not set enough type information when it generate pb file.

**Comment by bin2415** [comment]
I will set the type of block from disassemblers [here](https://github.com/junxzm1990/x86-sok/blob/d3b7391d0dd3a43c6cfa0904d8c648f5582fede4/compare/compareCFG.py#L294)

**Comment by cL0und** [comment]
Oh, sorry I did not read this part of code carefully, it seems like you parse the BB type during comparison.

**Comment by cL0und** [comment]
I think there is an ambiguity error in the value of non-return, in the IDA script you use [0x20](https://github.com/junxzm1990/x86-sok/blob/6c689fcad64b1156faed3f0cb7a68a9cdb751d0f/disassemblers/ida/idaBlocks.py#L56) as type id but in BlockUtil.py you use [0x8](https://github.com/junxzm1990/x86-sok/blob/d3b7391d0dd3a43c6cfa0904d8c648f5582fede4/extract_gt/BlockUtil.py#L269) as type id.

Besides, there seems like another error in the compareTailCall.py,  [sur_addr](https://github.com/junxzm1990/x86-sok/blob/d3b7391d0dd3a43c6cfa0904d8c648f5582fede4/compare/compareTailCall.py#L289) and [suc_addr](https://github.com/junxzm1990/x86-sok/blob/d3b7391d0dd3a43c6cfa0904d8c648f5582fede4/compare/compareTailCall.py#L293) should be the same variable.
