### ISSUE TITLE
Awaiting response... 502 Bad Gateway

### ISSUE THREAD

**Issue by NobinPegasus** [junxzm1990/x86-sok#19]
While using Example 2: compile coreutils instructions it shows

`wget -c https://mirror.powerfly.ca/gnu/coreutils/coreutils-8.30.tar.xz --no-check-certificate`

HTTP request sent, awaiting response... 502 Bad Gateway
2022-10-23 14:14:30 ERROR 502: Bad Gateway

**Comment by bin2415** [comment]
Hello, the link of `coreutils` is deprecated. Could you try `wget -c https://ftp.gnu.org/gnu/coreutils/coreutils-8.30.tar.xz`?

**Comment by NobinPegasus** [comment]
Yes. I had used it already.
It works thanks!
