### ISSUE TITLE
Matching func start virtual address to binary bytes

### ISSUE THREAD

**Issue by jupiterepoch** [junxzm1990/x86-sok#2]
Hi, thank you for this wonderful toolchain you developed. I wonder if there is a way I can match the function start virtual addresses to the binary bytes? I am trying to feed it as ground truth to another model. Thank you!

**Comment by junxzm1990** [comment]
Hi,

Just want to clarify a bit: by "start virtual address", you mean the starting address when the function is loaded into memory, right? If that's the case, you can run "readelf" to get a match between the virtual address of the text segment and the offset of the text segment in the binary file. Then: [offset of the function in the binary file] = [start address of the function] - [virtual address of the text segment] + [offset of the text segment in the binary file].

Hope it helps -:)

**Comment by jupiterepoch** [comment]
Thanks!
