### ISSUE TITLE
Sok appears to miss some functions.

### ISSUE THREAD

**Issue by thaddywu** [junxzm1990/x86-sok#5]
Hi, thanks so much for this wonderful tool. But I found SOK can't correctly resolve some functions from binary. Here below is an example in which SOK missed some functions. (e.g. _start, _dl_relocate_static_pie)

https://drive.google.com/file/d/1227_Am9DKcdtXN0T03297ecMyOmfqD2K/view?usp=sharing
This is a simple program compiled with -O2 -m32 flags using your gcc. Could you please take a look at this?

**Comment by bin2415** [comment]
Thanks for reporting. There are some functions that may not instrumented by our toolchains. The function are listed [here](https://github.com/junxzm1990/x86-sok/blob/master/compare/compareFuncs.py#L23). As for `_dl_relocate_static_pie` function, it is in [glibc](https://code.woboq.org/userspace/glibc/elf/dl-reloc-static-pie.c.html#27), so the glibc should be compiled by the our gcc toolchains and the [environment](https://github.com/junxzm1990/x86-sok/blob/master/gt/gcc32.rc) should be set properly.

**Comment by thaddywu** [comment]
Thanks so much for your quick response. Just to clarify that you said some functions may not be instrumented, and I see `_dl_relocate_static_pie` is also included in that list you just posted. So I believe I have used the correct version of glibc compiled by your toolchain.

I have also seen function `__i686.get_pc_thunk.bx` missed by SOK. Though not being listed, I guess it comes from the same reason. But I have no idea why your gcc toolchains always shoot out this function into binaries in my environment while I don't see it in your binaries from [the whole test suite](https://drive.google.com/file/d/1kwkEBS5DCpe_coWPXenDc8qO1Vjv_EwX/view?usp=sharing). Is it caused by the difference from environments? Mine is `Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-151-generic x86_64)`.

**Comment by bin2415** [comment]
My environment is also `Ubuntu 18.04 LTS`.

One possible reason is that `__i686.get_pc_thunk.reg` is defined in libc([here](https://github.com/bminor/glibc/blob/master/sysdeps/i386/sysdep.h#L31)). You could try to export CFLAGS like [this](https://github.com/junxzm1990/x86-sok/blob/master/gt/gcc32.rc#L12) and compile the program with the CFLAGS.

**Comment by thaddywu** [comment]
Thanks quite a lot for your kind reply! That really helps me a lot :)
