### ISSUE TITLE
Compile fortran with clang

### ISSUE THREAD

**Issue by thaddywu** [junxzm1990/x86-sok#6]
Hi,  thanks so much for your kind reply to my previous issue.

I got another issue that I find it intractable to use clang to compile benchmarks containing Fortran programs. I see compiler `gfortran-8.1` under the folder `$SOKPATH/build/executable_gcc/bin` but don't see any Fortran compiler under `$SOKPATH/gt/build/build_clang/bin`. I'm not sure if I missed any one?

To the best of my knowledge, Clang does not support Fortran. But I see `cactusADM_base.amd64-m64-ccr-O3`(Fortran benchmarks) in your test suite. Could you please let me how to compile Fortran programs with clang?

**Comment by bin2415** [comment]
Thanks for the reporting! I just checked the config file of CPU2006, I realized that I put the path of `gfortran-8.1` to compile the `cactusADM_base.amd64-m64-ccr-O3`. That means it is compiled by gcc compiler. Sorry for the mistake.
