### ISSUE TITLE
Compare the result - ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by akshithg** [junxzm1990/x86-sok#7]
`python3 compareInsts.py -b ./path/to/test_switch -g ./path/to/test_switch.gt -c /tmp/gtRef_test_switch.pb` throws a ZeroDivisionError: division by zero.

Am I doing this right?

**Comment by bin2415** [comment]
The file `/tmp/gtRef_test_switch.pb` is the ground truth file that contains cross references, it does not contain instructions. So if you want to compare the instructions, please pass the path of compared instructions from disassemblers(such as Angr, Ghidra and etc.)
